# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)

language:
    - objective-c

env:
    - TOOLCHAIN=libcxx CONFIG=Release
    - TOOLCHAIN=libcxx CONFIG=Debug
    - TOOLCHAIN=xcode CONFIG=Release
    - TOOLCHAIN=xcode CONFIG=Debug
    - TOOLCHAIN=ios-nocodesign-arm64 CONFIG=Release
    - TOOLCHAIN=ios-nocodesign-arm64 CONFIG=Debug
    - TOOLCHAIN=ios-nocodesign-armv7 CONFIG=Release
    - TOOLCHAIN=ios-nocodesign-armv7 CONFIG=Debug
    # - TOOLCHAIN=analyze CONFIG=Release (error in OpenCV)
    # - TOOLCHAIN=analyze CONFIG=Debug

install:
    - brew install cmake
    - brew install python3
    - brew install glfw3
    - brew install glew
    # install cmake toolchains and script
    - POLLY_VERSION="0.7.8"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
    # -- end
    # install cmake
    - CMAKE_TAG="3.3.2-p0"
    - CMAKE_VERSION="3.3.2"
    - wget "https://github.com/ruslo/CMake/releases/download/v${CMAKE_TAG}/cmake-${CMAKE_VERSION}-Darwin-x86_64.tar.gz"
    - tar xf "cmake-${CMAKE_VERSION}-Darwin-x86_64.tar.gz"
    - export PATH="`pwd`/cmake-${CMAKE_VERSION}-Darwin-x86_64/bin:${PATH}"
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end

script:
    - build.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose --fwd HUNTER_CONFIGURATION_TYPES=${CONFIG} --discard 10
